BookStoreMVC/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace BookStoreMVC.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [Display(Name = "Year Published")]
        public int? YearPublished;

        [Display(Name ="Number of pages")]
        public int? NumPages { get; set; }

        public string? Description { get; set; }

        [StringLength(50)]
        public string? Publisher { get; set; }

        [Display(Name = "Front Page")]
        public string? FrontPage { get; set; }

        [Display(Name = "Download URL")]
        public string? DownloadUrl { get; set; }

        [Display(Name = "Author")]
        [Required]
        public int AuthorId { get; set; }
        public Author? Author { get; set; }

        public ICollection<Review>? Reviews { get; set; }
        public ICollection<UserBooks>? Users { get; set; }
        public ICollection<BookGenre>? BookGenres { get; set;}
    }
}

BookStoreMVC/Controllers/BooksController.cs
using BookStoreMVC.Areas.Identity.Data;
using BookStoreMVC.Data;
using BookStoreMVC.Models;
using BookStoreMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Razor.Language.Extensions;
using Microsoft.EntityFrameworkCore;
using System.Data;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace BookStoreMVC.Controllers
{
    public class BooksController : Controller
    {
        private readonly BookStoreMVCContext _context;
        private readonly IHostingEnvironment webHostEnvironment;
        private readonly UserManager<BookStoreMVCUser> _userManager;

        public BooksController(BookStoreMVCContext context, IHostingEnvironment hostEnvironment, UserManager<BookStoreMVCUser> userManager)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
            _userManager = userManager;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString, string BookGenre)
        {
            IQueryable<BookGenre> books = _context.bookGenres.AsQueryable();
            IQueryable<string> genreQuery = _context.Genre.Distinct().Select(g => g.GenreName).Distinct();

            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Book.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(BookGenre))
            {
                books = books.Where(s => s.Genre.GenreName == BookGenre);
            }

            books = books.Include(b => b.Book).ThenInclude(b => b.Author);

            var bookGenreVM = new BookGenreViewModel
            {
                Genre = new SelectList(await genreQuery.ToListAsync()),
                Books = await books.Select(s => s.Book).Distinct().ToListAsync(),
                Reviews = await _context.Review.ToListAsync()
            };

            return View(bookGenreVM);
        }

        // GET: My Books
        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyBooks(string searchString)
        {
            var usr = await _userManager.GetUserAsync(HttpContext.User);
            IQueryable<UserBooks> books = _context.userBooks.AsQueryable().Where(s => s.AppUser == usr.Email);
            IQueryable<string> genreQuery = _context.Genre.Distinct().Select(g => g.GenreName).Distinct();
            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Book.Title.Contains(searchString));
            }

            books = books.Include(b => b.Book).ThenInclude(b => b.Author);

            var bookGenreVM = new BookGenreViewModel
            {
                Books = await books.Select(s => s.Book).Distinct().ToListAsync(),
                Reviews = await _context.Review.ToListAsync()
            };

            return View(bookGenreVM);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            // Do you own this book ?
            string purchesed = "No";
            var usr = await _userManager.GetUserAsync(HttpContext.User);
            if (usr != null)
            {
                var do_you_own_it = await _context.userBooks.Where(b => b.BookId == id && b.AppUser == usr.Email).FirstOrDefaultAsync();
                if (do_you_own_it != null)
                {
                    purchesed = "Yes";
                }
                ViewBag.Email = usr.Email;
            }
            else
            {
                ViewBag.Email = null;
            }
            // Get the reviews of this book
            var all_review = await _context.Review.Where(b => b.BookId == id).ToListAsync();

            var bookDetailsVM = new BookDetails
            {
                Book = book,
                Reviews = all_review,
                Purchesed = purchesed
            };
            return View(bookDetailsVM);
        }

        // GET: Books/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            CreateBookGenreViewModel viewModel = new CreateBookGenreViewModel
            {
                Book = new Book(),
                GenreList = new MultiSelectList(_context.Genre.AsEnumerable(), "Id", "GenreName"),
                SelectedGenres = Enumerable.Empty<int>()
            };
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FullName");
            return View(viewModel);
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CreateBookGenreViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.Image != null)
                {
                    string uniqueFileName = UploadedFile(viewModel);
                    viewModel.Book.FrontPage = uniqueFileName;
                }
                if (viewModel.PDF != null)
                {
                    string uniqueFileName = UploadedFile(viewModel);
                    viewModel.Book.DownloadUrl = uniqueFileName;
                }
                _context.Add(viewModel.Book);
                await _context.SaveChangesAsync();
                if (viewModel.SelectedGenres != null)
                {
                    foreach (int genreId in viewModel.SelectedGenres)
                    {
                        _context.bookGenres.Add(new BookGenre { BookId = viewModel.Book.Id, GenreId = genreId });
                    }
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FullName", viewModel.Book.AuthorId);
            return View(viewModel);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = _context.Book.Where(m => m.Id == id).Include(m => m.BookGenres).First();
            if (book == null)
            {
                return NotFound();
            }

            CreateBookGenreViewModel viewModel = new CreateBookGenreViewModel
            {
                Book = book,
                GenreList = new MultiSelectList(_context.Genre.AsEnumerable().OrderBy(s => s.GenreName), "Id", "GenreName"),
                SelectedGenres = book.BookGenres.Select(s => s.GenreId)
            };
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FullName", book.AuthorId);
            return View(viewModel);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, CreateBookGenreViewModel viewModel)
        {
            if (id != viewModel.Book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (viewModel.Image != null)
                    {
                        string uniqueFileName = UploadedFile(viewModel);
                        viewModel.Book.FrontPage = uniqueFileName;
                    }
                    if (viewModel.PDF != null)
                    {
                        string uniqueFileName = UploadedFile(viewModel);
                        viewModel.Book.DownloadUrl = uniqueFileName;
                    }
                    _context.Update(viewModel.Book);
                    await _context.SaveChangesAsync();
                    IEnumerable<int> newGenresList = viewModel.SelectedGenres;
                    IEnumerable<int> prevGenresList = _context.bookGenres.Where(s => s.BookId == id).Select(s => s.GenreId);
                    IQueryable<BookGenre> toBeRemoved = _context.bookGenres.Where(s => s.BookId == id);
                    if (newGenresList != null)
                    {
                        toBeRemoved = toBeRemoved.Where(s => !newGenresList.Contains(s.GenreId));
                        foreach (int genreId in newGenresList)
                        {
                            if (!prevGenresList.Any(s => s == genreId))
                            {
                                _context.bookGenres.Add(new BookGenre { GenreId = genreId, BookId = id });
                            }
                        }
                    }
                    _context.bookGenres.RemoveRange(toBeRemoved);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(viewModel.Book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

BookStoreMVC/Controllers/ReviewsController.cs
using BookStoreMVC.Areas.Identity.Data;
using BookStoreMVC.Data;
using BookStoreMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace BookStoreMVC.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly BookStoreMVCContext _context;
        private readonly UserManager<BookStoreMVCUser> _userManager;

        public ReviewsController(BookStoreMVCContext context, UserManager<BookStoreMVCUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Reviews
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var bookStoreMVCContext = _context.Review.Include(r => r.Book);
            return View(await bookStoreMVCContext.ToListAsync());
        }

        // GET: Reviews/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        [Authorize]
        public async Task<IActionResult> Create(int id)
        {
            var usr = await _userManager.GetUserAsync(HttpContext.User);

            // Keeping track of who is making the review
            ViewData["User"] = usr.Email;
            if (User.IsInRole("Admin"))
            {
                ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title");
                return View();
            }

            // id must not be null if the user is logged in and is not the admin
            if (id == null)
            {
                return NotFound("Error");
            }

            // The user has to own the book
            var own = _context.userBooks.Where(s => s.BookId == id && s.AppUser == usr.Email).ToListAsync();
            if (own == null)
            {
                return NotFound("Error");
            }

            // Return a list of only one item
            var book = _context.Book.Where(b => b.Id == id);
            if (book.FirstOrDefaultAsync() == null)
            {
                return NotFound("Error");
            }
            ViewData["BookId"] = new SelectList(book, "Id", "Title"); ;
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("BookId,AppUser,Comment,Rating")] Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title", review.BookId);
            return View(review);
        }

        // GET: Reviews/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            var book = _context.Review.Include(b => b.Book).Where(b => b.Id == id).Select(b => b.Book).ToList();
            ViewData["BookId"] = new SelectList(book, "Id", "Title", review.BookId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BookId,AppUser,Comment,Rating")] Review review)
        {
            if (id != review.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Books");
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title", review.BookId);
            return View(review);
        }

        // GET: Reviews/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Review == null)
            {
                return Problem("Entity set 'BookStoreMVCContext.Review'  is null.");
            }
            var review = await _context.Review.FindAsync(id);
            if (review != null)
            {
                _context.Review.Remove(review);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Books");
        }

        private bool ReviewExists(int id)
        {
            return (_context.Review?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BookStoreMVC/Views/Books/Create.cshtml
@model BookStoreMVC.ViewModels.CreateBookGenreViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.NumPages" class="control-label"></label>
                <input asp-for="Book.NumPages" class="form-control" />
                <span asp-validation-for="Book.NumPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Description" class="control-label"></label>
                <input asp-for="Book.Description" class="form-control" />
                <span asp-validation-for="Book.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Publisher" class="control-label"></label>
                <input asp-for="Book.Publisher" class="form-control" />
                <span asp-validation-for="Book.Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="Image" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PDF" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="PDF" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="PDF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.AuthorId" class="control-label"></label>
                <select asp-for="Book.AuthorId" class ="form-control" asp-items="ViewBag.AuthorId"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Genres</label>
                <select asp-for="SelectedGenres" class="form-control js-example-basic-multiple" asp-items="Model.GenreList"> </select>
                <span asp-validation-for="SelectedGenres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $("#SelectedGenres").select2();
            $(".custom-file-input").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
        });
    </script>
}

BookStoreMVC/Views/Books/Delete.cshtml
@model BookStoreMVC.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumPages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FrontPage)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/@Html.DisplayFor(model => model.FrontPage)" height="500px" width="300px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DownloadUrl)
        </dt>
        <dd class = "col-sm-10">
            <a href="@Html.DisplayFor(model => model.DownloadUrl)">Download</a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.FullName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookStoreMVC/Views/Books/Details.cshtml
@model BookStoreMVC.ViewModels.BookDetails

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.NumPages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Publisher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.FrontPage)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/@Html.DisplayFor(model => model.Book.FrontPage)" height="500px" width="300px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.DownloadUrl)
        </dt>
        <dd class = "col-sm-10">
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin") || Model.Purchesed == "Yes")
            {
                <a href="~/pdfs/@Html.DisplayFor(model => model.Book.DownloadUrl)">Download</a>
            }
            else
            {
                <p>You don't have access to the link</p>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Author.FullName)
        </dd>
        <dt class="col-sm-2">
            <p>Reviews:</p>
        </dt>
        <dd class="col-sm-10">
            @if (Model.Reviews.Any())
            {
                @foreach(var review in Model.Reviews)
                {
                    @if(review.AppUser == ViewBag.Email)
                    {
                        <p>@review.AppUser : @review.Comment Rating: @review.Rating 
                        <a asp-controller="Reviews" asp-action="Edit" asp-route-id="@review.Id">Edit</a> |
                        <a asp-controller="Reviews" asp-action="Delete" asp-route-id="@review.Id"> Delete</a>
                        </p>
                    }else{
                        <p>@review.AppUser : @review.Comment Rating: @review.Rating </p>
                    }
                }
            }
        </dd>
    </dl>
</div>
<div>
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p><a asp-action="Edit" asp-route-id="@Model?.Book.Id">Edit</a>|</p>
}
@if (Model.Purchesed == "Yes")
{
    <a asp-controller="Reviews" asp-action="Create" asp-route-id="@Model?.Book.Id">Add review</a> 
}
    | <a asp-action="Index">Back to List</a>
</div>

BookStoreMVC/Views/Books/Edit.cshtml
@model BookStoreMVC.ViewModels.CreateBookGenreViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Book.Id" />
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.NumPages" class="control-label"></label>
                <input asp-for="Book.NumPages" class="form-control" />
                <span asp-validation-for="Book.NumPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Description" class="control-label"></label>
                <input asp-for="Book.Description" class="form-control" />
                <span asp-validation-for="Book.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Publisher" class="control-label"></label>
                <input asp-for="Book.Publisher" class="form-control" />
                <span asp-validation-for="Book.Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="Image" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PDF" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="PDF" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="PDF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.AuthorId" class="control-label"></label>
                <select asp-for="Book.AuthorId" class="form-control" asp-items="ViewBag.AuthorId"></select>
                <span asp-validation-for="Book.AuthorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Genres</label>
                <select asp-for="SelectedGenres" class="form-control js-example-basic-multiple" asp-items="Model.GenreList"> </select>
                <span asp-validation-for="SelectedGenres" class="text-danger"></span>
            </div>
            <input asp-for="Book.FrontPage" type="hidden"/>
            <input asp-for="Book.DownloadUrl" type="hidden" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            $("#SelectedGenres").select2();
            $(".custom-file-input").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
        });
    </script>
}